2024-02-07 19:34:37,572 INFO    MainThread:3024 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-02-07 19:34:37,573 INFO    MainThread:3024 [wandb_setup.py:_flush():76] Configure stats pid to 3024
2024-02-07 19:34:37,573 INFO    MainThread:3024 [wandb_setup.py:_flush():76] Loading settings from C:\Users\14055\.config\wandb\settings
2024-02-07 19:34:37,573 INFO    MainThread:3024 [wandb_setup.py:_flush():76] Loading settings from F:\Everything\PPO-based-Autonomous-Navigation-for-Quadcopters\wandb\settings
2024-02-07 19:34:37,573 INFO    MainThread:3024 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-07 19:34:37,573 INFO    MainThread:3024 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-07 19:34:37,573 INFO    MainThread:3024 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'loading_main.py', 'program_abspath': 'f:\\Everything\\PPO-based-Autonomous-Navigation-for-Quadcopters\\loading_main.py', 'program': 'f:\\Everything\\PPO-based-Autonomous-Navigation-for-Quadcopters\\loading_main.py'}
2024-02-07 19:34:37,573 INFO    MainThread:3024 [wandb_init.py:_log_setup():524] Logging user logs to F:\Everything\PPO-based-Autonomous-Navigation-for-Quadcopters\wandb\run-20240207_193437-f40yw5wi\logs\debug.log
2024-02-07 19:34:37,573 INFO    MainThread:3024 [wandb_init.py:_log_setup():525] Logging internal logs to F:\Everything\PPO-based-Autonomous-Navigation-for-Quadcopters\wandb\run-20240207_193437-f40yw5wi\logs\debug-internal.log
2024-02-07 19:34:37,573 INFO    MainThread:3024 [wandb_init.py:init():564] calling init triggers
2024-02-07 19:34:37,573 INFO    MainThread:3024 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'speed': 3}
2024-02-07 19:34:37,573 INFO    MainThread:3024 [wandb_init.py:init():614] starting backend
2024-02-07 19:34:37,573 INFO    MainThread:3024 [wandb_init.py:init():618] setting up manager
2024-02-07 19:34:37,574 INFO    MainThread:3024 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-07 19:34:37,576 INFO    MainThread:3024 [wandb_init.py:init():624] backend started and connected
2024-02-07 19:34:37,578 INFO    MainThread:3024 [wandb_init.py:init():716] updated telemetry
2024-02-07 19:34:37,604 INFO    MainThread:3024 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-02-07 19:34:37,823 INFO    MainThread:3024 [wandb_run.py:_on_init():2254] communicating current version
2024-02-07 19:34:38,066 INFO    MainThread:3024 [wandb_run.py:_on_init():2263] got version response upgrade_message: "wandb version 0.16.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-02-07 19:34:38,066 INFO    MainThread:3024 [wandb_init.py:init():800] starting run threads in backend
2024-02-07 19:34:41,272 WARNING MsgRouterThr:3024 [router.py:message_loop():77] message_loop has been closed
2024-02-07 19:34:43,231 ERROR   MainThread:3024 [wandb_init.py:init():1188] transport failed
Traceback (most recent call last):
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 1170, in init
    run = wi.init()
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 811, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
